// <auto-generated />
namespace ClassSignIn_Hackathon_BE.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class EditedTimeStamp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EditedTimeStamp));
        
        string IMigrationMetadata.Id
        {
            get { return "201808061628370_Edited TimeStamp"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
